spring.application.name=webnhac
musicapi.key=6abf08b6ae0ebebf4cf719480c75ad96
musicapi.base-url=https://api.musicapi.ai
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration